---
resolutions:
  rule_violations:
  - message: "The project SpdxDocumentFile::agora-verifier:.* has a dependency licensed under the ScanCode copyleft categorized license AGPL-3.0-only."
    reason: "LICENSE_ACQUIRED_EXCEPTION"
    comment: "The project is open source so it's normal that it's set as such."

  - message: "The package (Maven:default:agora-verifier.*|SpdxDocumentFile::(vfork|agora-(verifier|tally|results))):.* has the declared ScanCode copyleft catalogized license AGPL-3.0-only."
    reason: "DYNAMIC_LINKAGE_EXCEPTION"
    comment: "Those are open source projects by us (nVotes) so it's normal they have an open source license."

