name: Test the agora-verifier

on:
  push:
    branches:
    - master
    - '[0-9]+.[0-9]+.x'
    tags:
    - '**'
  pull_request:
    branches:
    - master
    - '[0-9]+.[0-9]+.x'

jobs:
  py:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install external dependencies
      run: sudo apt update && sudo apt install -y wget sharutils curl

    # source: https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html
    - name: Setup Scala, Sbt and Java 8
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"

    - name: Install internal dependencies
      run: |
        export INTERNAL_GIT_VERSION="master"
        git clone https://github.com/agoravoting/agora-tally.git
        cd agora-tally && git checkout "${INTERNAL_GIT_VERSION}" && cd ..
        mv agora-tally/agora_tally .

        git clone https://github.com/agoravoting/agora-results.git
        cd agora-results && git checkout "${INTERNAL_GIT_VERSION}" && cd ..
        mv agora-results/ agora-results2
        mv agora-results2/agora_results .
        mv agora-results2/agora-results .

    - name: Build the verifier
      run: |
        sbt clean proguard:proguard && ./package.sh

    - name: run unittests
      run: |
        python3 -m unittest
